import {chromium} from '@playwright/test';
import 'dotenv/config';
import mongoose from 'mongoose';
import assert from 'node:assert/strict';
import fs from 'node:fs';
if(process.env.GMAIL_APP_PASSWORD?.trim())throw new Error('Disable welcome email sending and restart the development server before running synthetic signup tests.');
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const email=`nest-smoke-${Date.now()}@example.com`;
fs.mkdirSync('test-results',{recursive:true});
try{
 await page.goto('http://localhost:5173');
 await page.getByRole('button',{name:'Add Sony WH-1000XM5 to bag',exact:true}).waitFor();
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Save Sony WH-1000XM5',exact:true}).click();
 await page.getByRole('button',{name:'Wishlist',exact:true}).click();
 assert.equal(await page.locator('.product').count(),1);
 await page.getByRole('button',{name:'Add Sony WH-1000XM5 to bag',exact:true}).click();
 await page.getByRole('button',{name:'Shopping bag',exact:true}).click();
 await page.getByRole('button',{name:'Sign in to checkout',exact:true}).click();
 await page.getByRole('button',{name:'Create an account',exact:true}).click();
 await page.getByLabel('Full name',{exact:true}).fill('Nest Smoke Test');
 await page.getByLabel('Email address',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill('NestSmoke!2036');
 await page.screenshot({path:'test-results/signup.png'});
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Shopping bag',exact:true}).click();
 await page.getByRole('button',{name:'Continue to checkout',exact:true}).click();
 await page.getByLabel('Mobile number').fill('9876543210');
 await page.getByLabel('Street address').fill('123 Test Street, Test Nagar');
 await page.getByLabel('City',{exact:true}).fill('Bengaluru');
 await page.getByLabel('State',{exact:true}).fill('Karnataka');
 await page.getByLabel('PIN code').fill('560001');
 await page.getByRole('button',{name:/Place order/}).click();
 await page.getByText('It’s officially yours.').waitFor();
 await page.getByRole('button',{name:'View your order',exact:true}).click();
 await page.locator('.order').waitFor();
 assert.equal((await page.locator('.status').innerText()).toLowerCase(),'confirmed');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 if(await page.getByLabel('Full name',{exact:true}).count())await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
 await page.getByLabel('Email address',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill('NestSmoke!2036');
 await page.locator('form').filter({has:page.getByLabel('Email address')}).getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://localhost:5173');
 await page.locator('.product').first().waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Mobile layout must not overflow');
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: storefront, wishlist, bag, MongoDB signup, COD checkout, persisted order, login, mobile layout, and browser runtime.');
}finally{
 await browser.close();
 await mongoose.connect(process.env.MONGODB_URI);
 const users=mongoose.connection.collection('users');
 const fixture=await users.findOne({email});
 if(fixture){await mongoose.connection.collection('orders').deleteMany({user:fixture._id});await users.deleteOne({_id:fixture._id});}
 await mongoose.disconnect();
}
